config/routes.rb
Rails.application.routes.draw do
  resources :labels
  get 'sessions/new'
  resources :tasks
  resources :users, only: [:new, :create, :show]
  resources :sessions, only: [:new, :create, :destroy]
  root to: 'tasks#index'
  namespace :admin do
    resources :users
  end
end

app/models/task.rb
class Task < ApplicationRecord
  validates :title, presence: true
  validates :content, presence: true
  validates :dead_line, presence: true
  validates :status, presence:true
  scope :recent, -> { order(created_at: :desc)}
  scope :over, -> { order(dead_line: :asc)}
  scope :search_title, ->  (title) {where('title LIKE ?', "%#{ title }%")}
  scope :search_status, -> (status) {where(status: status)}
  scope :search_priority, -> (priority){ where(priority: priority) }
  enum priority: { 高: 0, 中:1, 低:2 }
  belongs_to :user
  has_many :labellings, dependent: :destroy
  has_many :labels, through: :labellings
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  before_action :login_require
  def index
    @tasks = current_user.tasks
    @tasks = @tasks.page(params[:page]).per(5)
    # @tasks = @tasks.joins(:labels).where(labels: {id: params[:label_id]}) if params[:label_id].present?
    if params[:sort_expired] == "true"
      @tasks = @tasks.over
    elsif params[:sort_expired] == "false"
      @tasks = @tasks.recent
    end

    if params[:task].present?
      if params[:task][:priority].present?
        @tasks = @tasks.search_priority(params[:task][:priority])
      end

      if params[:task][:title].present? && params[:task][:status].present?
        @tasks = @tasks.search_title(params[:task][:title])
        @tasks = @tasks.search_status(params[:task][:status])
      elsif params[:task][:title].present?
          @tasks = @tasks.search_title(params[:task][:title])
      elsif params[:task][:status].present?
          @tasks = @tasks.search_status(params[:task][:status])
      end

      if params[:task][:label_id].present?
        @labelling = Labelling.where(label_id: params[:task][:label_id]).pluck(:task_id)
        @tasks = @tasks.where(id: @labelling)
      end
    end
  end

  def new
    @task = Task.new
  end

  def show

  end

  def edit

  end

  def update
    if @task.update(task_params)
      flash[:notice] = I18n.t('notice.task_is_updated')
      redirect_to tasks_path
    else
      render :edit
    end
  end

  def create
    #current_userのuser_idを入れる
    @task = current_user.tasks.new(task_params)
    if @task.save
    flash[:notice] = I18n.t('notice.task_is_posted')
    redirect_to tasks_path
    else
      render :new
    end
  end

  def destroy
    @task.destroy
    flash[:notice] = I18n.t('notice.task_is_deleted')
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :content, :dead_line, :status, :priority, label_ids: [])
  end

  def set_task
    @task = current_user.tasks.find(params[:id])
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<%= form_with(model:@task, local: true) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= @task.errors.count %>件のエラーがあります。</h2>
      <ul>
        <% @task.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="col-md-4 new_form">

    <div class = "task-title">
      <%= f.label :title %>
      <%= f.text_field :title, class:'form-control col-md-6' %>
    </div>

    <div class="task-content">
      <%= f.label :content %>
      <%= f.text_area :content, class:'form-control col-md-6' %>
    </div>

    <div class="dead_line">
      <%= f.label :dead_line %>
      <%= f.datetime_select :dead_line, class:'form-control col-md-6' %>
    </div>

    <div class ="status">
      <%= f.label :status  %>
      <%= f.select :status, ["未着手", "着手中", "完了"], class:'form-control col-md-6' %>
    </div>

    <div class="priority">
      <%= f.label :priority %>
      <%= f.select :priority, ["高", "中","低"], class:'form-control col-md-6' %>
    </div>

    <div class="label">
      <% Label.all.each do |label| %>
        <%= f.check_box :label_ids, { multiple:true, checked: label[:checked], disabled: label[:disabled], include_hidden: false }, label[:id] %>
        <label class="label label-default"><%= label.name %></label>
      <% end %>
    </div>


    <%= f.submit class:'btn btn-primary' %>
  <% end %>
  </div>

app/views/tasks/edit.html.erb
<h1>Edit Task</h1>
<%= render 'form', task:@task %>

app/views/tasks/index.html.erb
<h1>Taskを検索する</h1>
<div class="container">
  <div class="col-md-6 task_index">
    <p id="notice"><%= notice %></p>

    <p><%=form_with(model: Task.new, url: tasks_path, method: :get, local: true) do |f| %></p>
        <div class="form-group">
          <%= f.label :search_status, t('sort.search_status') %>
          <%= f.select :status, ["未着手", "着手中", "完了"], {include_blank:true, selected: 0} %>
        </div>
        <div class="form-group">
          <%= f.label :search_title, t('sort.search_title') %>
          <%= f.text_field :title, placeholder: '検索するタイトルを入力してください', class:'form-control'%>
        </div>
        <div class="form-group">
          <%= f.label :priority, t('sort.search_priority') %>
          <%= f.select :priority, ["高", "中", "低"], {include_blank:true, selected: 0} %>
        </div>
        <div class="form-group">
          <%= f.label :label_name, "ラベル検索" %>
          <%= f.select :label_id, Label.all.collect.pluck(:name, :id), include_blank: true, selected: 0 %>
        </div>
        <%= f.submit "検索する", class: "btn btn-primary" %>
      <% end %>
  </div>
</div>


<h3><%= t('view_title.models.task.index') %> </h3>
<%= link_to t('link_to.models.task.dead_line'), tasks_path(sort_expired: "true") %><br>
<%= link_to t('link_to.models.task.created_at'), tasks_path(sort_expired: "false") %>

<table class="table">
  <thead>
  <tr>
    <th>ユーザー名</th>
    <th><%= t('activerecord.attributes.task.title') %></th>
    <th><%= t('activerecord.attributes.task.content') %></th>
    <th><%= t('activerecord.attributes.task.created_at') %></th>
    <th><%= t('activerecord.attributes.task.dead_line') %></th>
    <th><%= t('activerecord.attributes.task.status') %></th>
    <th><%= "優先順位" %></th>
    <th colspan="3"></th>
    <th><%= "登録タグ" %></th>
  </tr>
  </thead>

  <tbody>
  <% @tasks.each do |task| %>
    <tr class="task_row">
      <td><%= task.user.name %></td>
      <td><%= task.title %></td>
      <td><%= task.content %></td>
      <td><%= task.created_at.strftime('%Y/%m/%d %H:%M')%></td>
      <td><%= task.dead_line.strftime('%Y/%m/%d %H:%M')%></td>
      <td><%= task.status %></td>
      <td><%= task.priority %></td>
      <td><%= link_to t('link_to.models.task.show'), task_path(task.id), class: 'btn btn-info' %></td>
      <td><%= link_to t('link_to.models.task.edit'), edit_task_path(task.id), class: 'btn btn-warning' %></td>
      <td><%= link_to t('link_to.models.task.delete'), task_path(task.id), method: :delete, class: 'btn btn-danger', data: { confirm: I18n.t('notice.comfirm_task_delete') } %></td>
      <td>
        <% task.labels.each do |label| %>
          <%= label.name %>
        <% end %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>
<br>

<div class="text-center">
  <%= paginate @tasks %>
</div>

app/views/tasks/new.html.erb
<h1><%= t('view_title.models.task.new') %></h1>
<%= render 'form', task:@task %>

app/views/tasks/show.html.erb
<h1>Task詳細画面</h1>
<div class="show_path">
  <h4><%=t('activerecord.attributes.task.title') %>: <%= @task.title %></h4>
  <h4><%=t('activerecord.attributes.task.content') %>:<%= @task.content %></h4>
  <h4><%=t('activerecord.attributes.task.created_at') %>:<%=@task.created_at.strftime('%Y/%m/%d %H:%M')%></h4>
  <h4><%=t('activerecord.attributes.task.dead_line') %>:<%= @task.dead_line.strftime('%Y/%m/%d %H:%M') %></h4>
  <h4><%=t('activerecord.attributes.task.status') %>:<%= @task.status %></h4>
  <h4><%=t('activerecord.attributes.task.priority') %>:<%=@task.priority %></h4>
  <h4>登録ラベル:
  <% @task.labels.each do |label| %>
    <%=label.name %>
  <% end %>
  </h4>
  <%= link_to t('link_to.models.task.back'), tasks_path, class:'btn btn-danger' %>
</div>