config/routes.rb
Rails.application.routes.draw do
  resources :labels
  get 'sessions/new'
  resources :tasks
  resources :users, only: [:new, :create, :show]
  resources :sessions, only: [:new, :create, :destroy]
  root to: 'tasks#index'
  namespace :admin do
    resources :users
  end
end

app/models/user.rb
class User < ApplicationRecord
  before_destroy :ensure_last_admin
  before_validation { email.downcase! }
  validates :email, uniqueness: true
  validates :name,  presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum:255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  validates :password, presence:true, length: { minimum: 6 }, allow_nil: true
  has_secure_password
  has_many :tasks, dependent: :destroy


  private
  def ensure_last_admin
    if self.admin == true
      if User.all.where(admin: true).count == 1
      throw (:abort)
      end
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_admin
  def index
    @users = User.all.includes(:tasks)
  end

  def show

  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to admin_user_path(@user.id), notice: "ユーザー登録をしました！"
    else
      render :new
    end
  end

  def update
    if @user.update(user_params)
      redirect_to admin_user_path(@user.id)
    else
      render :edit
    end
  end

  def destroy
    if @user.destroy
      redirect_to admin_users_path, notice: "ユーザーを削除しました！"
    else
      redirect_to admin_users_path, notice: '最後の管理者は削除できません'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :admin, :password, :password_confirmation)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def require_admin
    # binding.pry
    unless current_user.admin?
      flash[:notice] = '管理者だけがアクセスできます'
      redirect_to root_url
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :login_require, only:[:show]
  before_action :correct_user, only:[:show ]
  def new
    if logged_in?
      redirect_to user_path(current_user.id)
    else
      @user = User.new
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user.id)
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.erb
<%= form_with(model: [:admin, @user], local:true) do |f| %>
<div class="col-md-4 new_form">
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :email %>
    <%= f.text_field :email, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :password  %>
    <%= f.password_field :password, class: 'form-control' %>
  </div>

  <div class="form-check">
    <%= f.label :admin, t('activerecord.attributes.user.admin'), class: 'form-check-label'  %>
    <%= f.check_box :admin, {}, 'true', 'false'  %>
  </div>

  <div class="form-group">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, class: 'form-control' %>
  </div>
  <%=f.submit t('view.Register_new_user'), class: 'btn btn-primary' %>
</div>
<% end %>

app/views/admin/users/edit.html.erb
<h1>ユーザーの編集画面</h1>
<%= form_with(model: [:admin, @user], local:true) do |f| %>
  <div class="col-md-4 new_form">
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :email %>
      <%= f.text_field :email, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :password  %>
      <%= f.password_field :password, class: 'form-control' %>
    </div>

    <div class="form-check">
      <%= f.label :admin, t('activerecord.attributes.user.admin'), class: 'form-check-label'  %>
      <%= f.check_box :admin, {}, 'true', 'false'  %>
    </div>

    <div class="form-group">
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>
    </div>
    <%=f.submit t('view.Register_new_user'), class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/admin/users/index.html.erb
<h1>管理画面のユーザー　一覧画面だよ！</h1>
<table class="table">
  <thead>
    <tr>
      <th>ユーザー名</th>
      <th>ユーザー名</th>
      <th>ユーザーのタスク作成数</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr class="task_row">
        <td>ユーザー名:<%=link_to user.name, admin_user_path(user.id) %></td>
        <td>タスクの作成数:<%= user.tasks.count %></td>
        <td><%= link_to t('link_to.models.admin_user.show'), edit_admin_user_path(user.id) , class: 'btn btn-info' %></td>
        <td><%= link_to t('link_to.models.admin_user.delete'), admin_user_path(user.id), class: 'btn btn-danger',
                        method: :delete, data: { confirm: 'Are you sure to delete this user?'} %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/users/new.html.erb
<h1>管理者ユーザー登録</h1>
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= render 'form', user:@user %>

app/views/admin/users/show.html.erb
<h1><%= @user.name %>のページ</h1>
<div class="text-center">
  <p>メールアドレス: <%= @user.email %></p>
  <%= link_to t('link_to.models.admin_user.index'), admin_users_path, class: 'btn btn-primary' %>
</div>

<table class="table">
  <thead>
    <tr>
      <th>タスク名</th>
      <th>内容</th>
      <th>投稿時間</th>
      <th>期限</th>
      <th>ステータス</th>
      <th>優先順位</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
  <% @user.tasks.each do |task| %>
    <tr class="task_row">
      <th><%= task.title %></th>
      <th><%= task.content %></th>
      <td><%= task.created_at.strftime('%Y/%m/%d %H:%M')%></td>
      <td><%= task.dead_line.strftime('%Y/%m/%d %H:%M')%></td>
      <th><%= task.status %></th>
      <th><%= task.priority %></th>
    </tr>
  <% end %>
  </tbody>
</table>