config/routes.rb
Rails.application.routes.draw do
  resources :labels
  get 'sessions/new'
  resources :tasks
  resources :users, only: [:new, :create, :show]
  resources :sessions, only: [:new, :create, :destroy]
  root to: 'tasks#index'
  namespace :admin do
    resources :users
  end
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbarEexample1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">タスク作成アプリ</a>
    </div>
      <ul class="nav navbar-nav">
        <li><%= link_to "タスク登録", new_task_path %></li>
        <li><%= link_to "タスク一覧", tasks_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li><%= link_to "プロフィール", user_path(current_user.id) %></li>
          <li><%= link_to "ログアウト ", session_path(current_user.id), method: :delete %></li>
          <%# binding.pry %>
          <% if current_user.admin? %>
            <li><%= link_to "管理者用ユーザー一覧", admin_users_path %></li>
            <li><%= link_to "管理者ユーザー作成", new_admin_user_path %></li>
            <li><%= link_to "ラベルの作成", new_label_path %></li>
          <% end %>
        <% else %>
          <li><%= link_to "新規ユーザー登録", new_user_path %></li>
          <li><%= link_to "ログイン", new_session_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ManyoKadai</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'bootstrap_task', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>
    <%= render 'layouts/header' %>
    <%= yield %>
  </body>
</html>